language: csharp
mono: none
dotnet: 2.2
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
    - master
script:
  - chmod +x travis.sh
  - ./travis.sh
# matrix:
#   include:
#     - os: linux
#       dist: xenial
#     - os: osx
#       dotnet: 2.2
#       osx_image: xcode10.1