language: csharp
mono: none
dotnet: 6.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/StartupModules.Tests