language: csharp
mono: none
dotnet: 3.1
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/StartupModules.Tests
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      dotnet: 3.1.102
      osx_image: xcode11.2