language: csharp
mono: none
dotnet: 2.2
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
os:
  - linux
  - osx
osx_image: xcode8.3
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/StartupModules.Tests